@base_url = http://localhost:4561
@api_v = /v1
@boundary = ----MyBoundary
@jwt = jwt

### root page
GET {{base_url}}/ HTTP/1.1

### confirmation
GET {{base_url}}/check/echo HTTP/1.1

### test
GET {{base_url}}/check/sandbox HTTP/1.1

### user
POST {{base_url}}/v1/users/register HTTP/1.1
